config/routes.rb
Rails.application.routes.draw do

  resources :notes do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      put 'vote_multiple'
    end
  end

  get '/users/:id/edit' ,to: 'users#edit', as:'userEdit'
  post '/users/:id/edit' ,to: 'users#edit', as:'userEditp'
  patch "users/:id" => "users#update", as: "user_update"

  resources :votes

  resources :participants

  resources :notifications

  Rails.application.routes.draw do
    resources :users, controller: 'users', only: Clearance.configuration.user_actions
  end

  get 'whatis/index'

  resources :notes

  resources :boards

  resources :dynamics
  get '/dynamics/:id/info', to: 'dynamics#info', as: 'info'
  get '/dynamics/:id/addParticipant', to: 'dynamics#addParticipant', as: 'addParticipant'
  get '/dynamics/:id/addBoard', to: 'dynamics#addBoard', as: 'addBoard'
  get '/dynamics/:id/statistics', to: 'dynamics#statistics', as: 'statistics'
  get '/dynamics/:id/votingResults', to: 'dynamics#votingResults', as: 'votingResults'
  get '/boards/:id/addNote', to: 'boards#addNote', as: 'addNote'

  get '/boards/:id/moveNotes', to: 'boards#moveNotes', as: 'moveNotes'
  get '/boards/:id/votation', to: 'boards#votation', as: 'votation'

  get '/dynamics/:id/leave', to: 'dynamics#leave', as: 'leave'
  get '/dynamics/:id/activateVotation', to: 'dynamics#activateVotation', as: 'activateVotation'

  get 'box' => 'welcome#box'
  get 'design' => 'welcome#index'

  root 'dynamics#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :board
  belongs_to :dynamic
  has_many :votes
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to "/boards/#{@note.board_id}" }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
    @dynamic = Dynamic.where(id:@note.dynamic_id).last
    @dynamic.numerodenotas = @dynamic.numerodenotas + 1 
    @dynamic.save
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to "/dynamics/#{@note.dynamic_id}" }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    @i = Note.last
    Note.destroy(params[:notes])
      respond_to do |format|
        format.html { redirect_to (:back) }
        format.json { head :no_content }
      end
  end

  def update_multiple
    if (params.has_key?(:note))
      @board = params[:note][:board_id]
      @notes = Note.find(params[:notes])
      @notes.reject! do |note|
        note.update_attributes(:board_id => @board )
      end
      redirect_to "/dynamics/#{Board.where(id:@board).last.dynamic_id}"
    else
      redirect_to (:back)
    end
  end


  def vote_multiple
    @notes = Note.find(params[:notes])
    @notes.reject! do |note|
      Vote.create :participant_id => Participant.where(email:current_user.email,dynamic_id:note.dynamic_id).last.id , :dynamic_id => note.dynamic_id, :note_id => note.id
      @p= Participant.where(email:current_user.email,dynamic_id:note.dynamic_id).last
    end
    @p.vote= true
    @p.save
    Notification.create :user_id => current_user.id , :text => "You voted on dynamic #{Dynamic.where(id:@p.dynamic_id).last.name}", :estado => false
    redirect_to (:back)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:board_id, :text,:color,:email,:dynamic_id,:numerodanota)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>
    <div class="input-letter"><%= f.text_area :text,:placeholder=>"Text",:style => 'text-align:center;background-image: url("");',:class=>'form-control'   %></div>
  </div>
  <br>
  <div class="field">
    <%= select(:note,:color, [
      ['Turquoise', "notaAzul2 lifted"],
      ['Orange', "notaLaranja2 lifted"],
      ['Red', "notaRed2 lifted"],
      ['Yellow', "notaAmarelo2 lifted"],
      ['Blue', "notaAzulClaro3 lifted"],
      ['Purple', "notaRoxo2 lifted"],
      ['Brown', "notaCastanho2 lifted"],
      ['Green', "notaVerde2 lifted"],
    ])%>
  </div>
  <br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
  <br><br>
  <div class= "hh3">
    <%= link_to "/dynamics/#{@note.dynamic_id}" , method: :get , :class => "hvr-icon-back" do %> 
      Back to Board
    <% end %>
  </div>
  <br><br>
<% end %>

app/views/notes/edit.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render './dynamics/formTopBarN' %>
      <br><br><br>
      <div class="box-wall">   
        <div class="box-wall-text">
          <h3><i class="fa fa-paper-plane"></i></h3>
          <div class="serif">
        		<h1>Edit Note</h1>
        		<%= render 'form' %>
		        <br>
          </div>
        </div>
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
  </body>
</html>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>
<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.board %></td>
        <td><%= note.text %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board:</strong>
  <%= @note.board %>
</p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>