config/routes.rb
Rails.application.routes.draw do

  resources :notes do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      put 'vote_multiple'
    end
  end

  get '/users/:id/edit' ,to: 'users#edit', as:'userEdit'
  post '/users/:id/edit' ,to: 'users#edit', as:'userEditp'
  patch "users/:id" => "users#update", as: "user_update"

  resources :votes

  resources :participants

  resources :notifications

  Rails.application.routes.draw do
    resources :users, controller: 'users', only: Clearance.configuration.user_actions
  end

  get 'whatis/index'

  resources :notes

  resources :boards

  resources :dynamics
  get '/dynamics/:id/info', to: 'dynamics#info', as: 'info'
  get '/dynamics/:id/addParticipant', to: 'dynamics#addParticipant', as: 'addParticipant'
  get '/dynamics/:id/addBoard', to: 'dynamics#addBoard', as: 'addBoard'
  get '/dynamics/:id/statistics', to: 'dynamics#statistics', as: 'statistics'
  get '/dynamics/:id/votingResults', to: 'dynamics#votingResults', as: 'votingResults'
  get '/boards/:id/addNote', to: 'boards#addNote', as: 'addNote'

  get '/boards/:id/moveNotes', to: 'boards#moveNotes', as: 'moveNotes'
  get '/boards/:id/votation', to: 'boards#votation', as: 'votation'

  get '/dynamics/:id/leave', to: 'dynamics#leave', as: 'leave'
  get '/dynamics/:id/activateVotation', to: 'dynamics#activateVotation', as: 'activateVotation'

  get 'box' => 'welcome#box'
  get 'design' => 'welcome#index'

  root 'dynamics#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :dynamic
  has_many :votes

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
    @participants = Participant.all
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to "/dynamics/#{@participant.dynamic.id}", notice: '' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
      if(User.all.where(email:"user@ideatouch.pt").last.id!=nil)
        Notification.create :user_id => User.all.where(email:@participant.email).last.id , :text => "you were added to dynamic #{@participant.dynamic.name}", :estado => false
      end 
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to "/dynamics/#{@participant.dynamic_id}", notice: '' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:email, :dynamic_id,:avatar,:name,:vote)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<div class="hh4">
  <%= form_for @participant, :html => { :multipart => true } do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% @participant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name,:placeholder=>"nome",:style => 'text-align:center' %>
  </div>
  <br>
  <% if @participant.avatar_file_name!=nil %>
    <%= image_tag @participant.avatar.url(:medium), :class=> "img-thumbnail" %>
  <% end %>
  <div class="field">
    <h5><%= f.file_field :avatar %></h5>
  </div>
  <br>
  <div class="actions">
    <%= button_to "Submit", participants_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
</div>
<br><br>
<div class= "hh3">
  <%= link_to "/dynamics/#{@participant.dynamic.id}" , method: :get , :class => "hvr-icon-back" do %> 
    Back to Dynamic
  <% end %>
</div>
<br><br>
<% end %>

app/views/participants/_formTopBarP.html.erb
<div id="topo">
  <%= link_to dynamics_path , method: :get  do %>
    <div class="topo-Logo wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
      IDeaTouch
    </div>
  <% end %> 
  <%= link_to sign_out_path, method: :delete  do %>
    <div class="topo-perfil wow fadeInRight" data-wow-duration="0.6s" data-wow-delay="0.6s">
      <i class="fa fa-power-off"></i>
    </div>
  <% end %>

  <!-- sino notificaçoes -->
  <% if @notificationss!=0 %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="hvr-buzz-out">
        <div class="topo-perfil2 wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
          <i class="fa fa-bell"></i>
        </div>  
      </div>
    <% end %>
  <% else %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="topo-perfil wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
        <i class="fa fa-bell-o"></i>
      </div>
    <% end %>
    <!-- -->
  <% end %>
  <div class="topo-perfil wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.8s">
    <i class="fa fa-user"></i>
  </div>
  <%if @participant.dynamic ==1%>
    ola
  <%end %>
  <div class="topo-perfilF wow fadeInUp" data-wow-duration="1.0s" data-wow-delay="1.0s">
    <% if @participants.where(email:current_user.email, dynamic_id:@participant.dynamic.id).last.avatar_file_name!= nil %>
      <%= link_to  edit_participant_path(@participants.where(email:current_user.email, dynamic_id:@participant.dynamic.id).last.id) , method: :get  do %>
        <%= image_tag @participants.where(email:current_user.email, dynamic_id:@participant.dynamic.id).last.avatar.url(:medium) , size: "60x70" %>
      <% end %>
    <% else %>
      <div class= "avatar">
        <h2><i class="fa fa-user-secret"></i></h2>
      </div>
    <% end %>
  </div>
  <div class="topo-nome wow fadeInRight" data-wow-duration="1.5s" data-wow-delay="1.5s">
    <%if @participants.where(email:current_user.email, dynamic_id:@participant.dynamic.id).last.name != nil %>
      <div class="serif">
        <%=@participants.where(email:current_user.email, dynamic_id:@participant.dynamic.id).last.name%>
      </div>
    <% else %>
      <div class="serif">
        Edit your Avatar
      </div>
    <% end %>   
  </div>
</div>

app/views/participants/edit.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render 'formTopBarP' %>
      <br><br><br>
      <div class="box-wall">   
        <div class="box-wall-text">
          <h3>  <i class="fa fa-user-secret"></i></h3>
          <div class="serif">
            <h1>Edit Avatar</h1>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
  </body>
</html>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Dynamic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.dynamic %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>Invite People</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name -</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Email -</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Dynamic -</strong>
  <%= @participant.dynamic.name %>
</p>

<p>
  <strong>Avatar - </strong>
  <%= image_tag @participant.avatar.url(:medium) %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>