config/routes.rb
Rails.application.routes.draw do

  resources :notes do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      put 'vote_multiple'
    end
  end

  get '/users/:id/edit' ,to: 'users#edit', as:'userEdit'
  post '/users/:id/edit' ,to: 'users#edit', as:'userEditp'
  patch "users/:id" => "users#update", as: "user_update"

  resources :votes

  resources :participants

  resources :notifications

  Rails.application.routes.draw do
    resources :users, controller: 'users', only: Clearance.configuration.user_actions
  end

  get 'whatis/index'

  resources :notes

  resources :boards

  resources :dynamics
  get '/dynamics/:id/info', to: 'dynamics#info', as: 'info'
  get '/dynamics/:id/addParticipant', to: 'dynamics#addParticipant', as: 'addParticipant'
  get '/dynamics/:id/addBoard', to: 'dynamics#addBoard', as: 'addBoard'
  get '/dynamics/:id/statistics', to: 'dynamics#statistics', as: 'statistics'
  get '/dynamics/:id/votingResults', to: 'dynamics#votingResults', as: 'votingResults'
  get '/boards/:id/addNote', to: 'boards#addNote', as: 'addNote'

  get '/boards/:id/moveNotes', to: 'boards#moveNotes', as: 'moveNotes'
  get '/boards/:id/votation', to: 'boards#votation', as: 'votation'

  get '/dynamics/:id/leave', to: 'dynamics#leave', as: 'leave'
  get '/dynamics/:id/activateVotation', to: 'dynamics#activateVotation', as: 'activateVotation'

  get 'box' => 'welcome#box'
  get 'design' => 'welcome#index'

  root 'dynamics#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :dynamic
  has_many :notes
  accepts_nested_attributes_for :notes
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy, :addNote,:moveNotes,:moveNotes,:votation]
  before_action :require_login

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def addNote
    @dynamics = Dynamic.all
    @note= Note.new
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def votation
    @lim = Dynamic.where(id:@board.dynamic_id).last.votationnumber
    @dynamics = Dynamic.all
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def moveNotes
    @dynamics = Dynamic.all
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  # GET /boards/new
  def new
    @board = Board.new
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
  end

  # GET /boards/1/edit
  def edit
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.name!="all notes" and @board.name!="without board" and @board.save 
        format.html { redirect_to "/dynamics/#{@board.dynamic_id}"}
        format.json { render :show, status: :created, location: @board }
      else
        format.html { redirect_to "/dynamics/#{@board.dynamic_id}" }
        format.json { render :show, status: :created, location: @board }
      end
    end
      if @board.name==""
        @board.name="undefined"
        @board.save
      end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board}
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to "/dynamics/#{@board.dynamic_id}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :descricao, :dynamic_id,:color,notes_attributes: [ :text ])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <br><br>
    <div class="input-letter">
      <%= f.text_field :name ,:placeholder=>"Name",:style => 'text-align:center;background-image: url("");',:class=>'form-control'  %>
    </div>
  </div>
  <br>
  <div class="letrasInfo2">color: </div>
  <div class="field">
    <%= select(:board,:color, [
      ['Red', "boardRed"],
      ['Turquoise', "boardAzul"],
      ['Orange', "boardLaranja"],
      ['Yellow', "boardAmarelo"],
      ['Blue', "boardAzulClaro"],
      ['Purple', "boardRoxo"],
      ['Brown', "boardCastanho"],
      ['Green', "boardVerde"],
    ])%>
  </div>
  <br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
  <br><br>
  <div class= "hh3">
    <%= link_to "/dynamics" , method: :get , :class => "hvr-icon-back" do %> 
      Back to Dynamics
    <% end %>
  </div>
  <br><br>
<% end %>

app/views/boards/_formMoveNote.html.erb
<div class="linha"></div>

<%= form_tag update_multiple_notes_path, method: :put do %>            
  <% if @board.name != "without board"%>
    <% for note in @board.notes %>
      <div class="hvr-float">
      <div class = "hvr-curl-top-left wow bounceIn" data-wow-duration="0.5s" data-wow-delay="0.5s" >
      <div class="<%= note.color %>">
      <div class="textoo">
      <%= check_box_tag "notes[]", note.id %>
      <div class="hhp"><%= note.numerodanota%></div>
      <hh4><%= note.text %></hh4> 
      </div></div> 
      </div></div>
    <% end %>
  <% end %>
  <% if @board.name == "without board" %>
    <% for note in Note.where(board_id:(Board.where(dynamic_id: @board.dynamic,name:'all notes').last.id)) %>
      <div class="hvr-float">
      <div class = "hvr-curl-top-left wow bounceIn" data-wow-duration="0.5s" data-wow-delay="0.5s" >
      <div class="<%= note.color %>">
      <div class="textoo">
      <%= check_box_tag "notes[]", note.id %>
      <div class="hhp"><%= note.numerodanota%></div>
      <hh4><%= note.text %></hh4> 
      </div></div> 
      </div></div>
    <% end %>
  <% end %>
  <div class="linha"></div>
  <%= fields_for :note do |f| %>
    <div class= "letrasInfo">
      Choose the board
      <div class="field">
        <%= select(:note,:board_id, (Board.where.not(name:'all notes')& Board.where.not(name:'without board') & Board.where(dynamic_id:@board.dynamic_id)).map { |board| [board.name, board.id] })%>
      </div>
    </div>
  <% end %>
  <br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
  <br><br>
  <div class= "hh3">
    <%= link_to "/boards/#{@board.id}" , method: :get , :class => "hvr-icon-back" do %> 
      Back to Board
    <% end %>
  </div>
  <br>
<% end %>

app/views/boards/_formNote.html.erb
<%= form_for(@note) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>
    <div class="input-letter"><%= f.text_area :text,:placeholder=>"Text",:style => 'text-align:center;background-image: url("");',:class=>'form-control'   %></div>
  </div>
  <br>
  <div class="field">
    <%= select(:note,:color, [
      ['Turquoise', "notaAzul2 lifted"],
      ['Orange', "notaLaranja2 lifted"],
      ['Red', "notaRed2 lifted"],
      ['Yellow', "notaAmarelo2 lifted"],
      ['Blue', "notaAzulClaro3 lifted"],
      ['Purple', "notaRoxo2 lifted"],
      ['Brown', "notaCastanho2 lifted"],
      ['Green', "notaVerde2 lifted"],
    ])%>
  </div>
  <%= f.hidden_field :numerodanota, value: @dynamics.where(id:@board.dynamic_id).last.numerodenotas+1 %>
  <%= f.hidden_field :board_id, value: @board.id %>
  <%= f.hidden_field :dynamic_id, value: @board.dynamic_id %>
  <br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
  <br><br>
  <div class= "hh3">
    <%= link_to "/boards/#{@board.id}" , method: :get , :class => "hvr-icon-back" do %> 
      Back to Board
    <% end %>
  </div>
  <br><br>
<% end %>

app/views/boards/_formVotation.html.erb
<% if  Participant.where(email:current_user.email,dynamic_id:@board.dynamic_id).last.vote==false%>
  <h1>Voting</h1>
  <br>
  Vote at most in <%= Dynamic.where(@board.dynamic_id).last.votationnumber %> notes
  <div class="linha"></div>
  <%= form_tag vote_multiple_notes_path, method: :put do %>
  <% for note in Note.where(dynamic_id:@board.dynamic_id) %>
    <div class="hvr-float">
    <div class = "hvr-curl-top-left wow bounceIn" data-wow-duration="0.5s" data-wow-delay="0.5s" >
    <div class="<%= note.color %>">
    <div class="textoo">
    <%= check_box_tag "notes[]", note.id %>
    <div class="hhp"><%= note.numerodanota%></div>
    <hh4><%= note.text %></hh4> 
    </div></div> 
    </div></div>
  <% end %>
  <div class="linha"></div>
  <%= fields_for :note do |f| %>
  <% end %>
  <br><br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
<% end %>
<% else %>
  <h1>Your votes</h1>
  <div class="linha"></div>          
  <% for note in Note.where(id:Vote.select(:note_id).where(dynamic_id:@board.dynamic_id, participant_id: Participant.where(email:current_user.email,dynamic_id:@board.dynamic_id).last.id       )) %>
    <div class="hvr-float">
    <div class = "hvr-curl-top-left wow bounceIn" data-wow-duration="0.5s" data-wow-delay="0.5s" >
    <div class="<%= note.color %>">
    <div class="textoo">
    <div class="hhp"><%= note.numerodanota%></div>
    <hh4><%= note.text %></hh4> 
    </div></div> 
    </div></div>
  <% end %>
  <div class="linha"></div>
<% end %>
<br><br>
<div class= "hh3">
  <%= link_to "/boards/#{@board.id}" , method: :get , :class => "hvr-icon-back" do %> 
    Back to Board
  <% end %>
</div>
<br>

app/views/boards/addNote.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render './dynamics/formTopBarB' %>
      <br><br><br>
      <div class="box-wall">
        <div class="box-wall-text">
          <h3><i class="fa fa-paper-plane"></i></h3>
          <div class="serif">
            <h1>New Note</h1>
        	  <%= render 'formNote' %>
		        <br>
          </div>
        </div>
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
  </body>
</html>

app/views/boards/edit.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render './dynamics/formTopBarB' %>
      <br><br><br>
      <div class="box-wall">   
        <div class="box-wall-text">
          <h3><i class="fa fa-paper-plane"></i></h3>
          <div class="serif">
      		  <h1>Editing Board</h1>
        	  <%= render 'form' %>
	          <br>
          </div>
        </div>
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
  </body>
</html>

app/views/boards/index.html.erb
<div class ="qwe">
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Descricao</th>
      <th>Dynamic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= board.descricao %></td>
        <td><%= board.dynamic_id %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div>
  

app/views/boards/moveNotes.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render './dynamics/formTopBarB' %>
      <br><br><br>
      <div class="box-wall">   
        <h3><i class="fa fa-level-up"></i></h3>
        <div class="serif">
          <h1>Move Notes</h1>
        	<%= render 'formMoveNote' %>
		      <br>
        </div>
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
    <script>
      $(':checkbox').on('change', function () {
        $('input[type="submit"]').prop('disabled', !$(':checkbox:checked').length);
      }).change();
    </script>
  </body>
</html>

app/views/boards/votation.html.erb
<html>
  <head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render './dynamics/formTopBarB' %>
      <br><br><br>
      <div class="box-wall">   
        <h3><i class="fa fa-archive"></i></h3>
        <div class="serif">
  		    <%= render 'formVotation' %>
	  	    <br>
        </div>    
      </div>
    </div>

    <script src="js/wow.js"></script>
    <script>wow = new WOW({animateClass:'animated',offset:100,
      callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
      wow.init();
      document.getElementById('moar').onclick = function() {
        var section = document.createElement('section');
        section.className = 'section--purple wow fadeInDown';
        this.parentNode.insertBefore(section, this);};
    </script>
    <script>
      $(function() {
        $(".preload").fadeOut(10, function() {
          $(".content").fadeIn(10);        
        });
      });
    </script>
    <script>
      $('.submit_me').click(function() {
        $('form').submit();
        return false;
      });
    </script>
    <script>
      var lim = <%= @lim %>
      $('input[type=checkbox]').change(function(e){
        if ($('input[type=checkbox]:checked').length > lim) {
          $(this).prop('checked', false)
          alert("You can only select "+ lim + " checkbox's!");
       }
      })
    </script>
    <script>
      $(':checkbox').on('change', function () {
        $('input[type="submit"]').prop('disabled', !$(':checkbox:checked').length);
      }).change();
    </script>
  </body>
</html>