config/routes.rb
Rails.application.routes.draw do

  resources :notes do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      put 'vote_multiple'
    end
  end

  get '/users/:id/edit' ,to: 'users#edit', as:'userEdit'
  post '/users/:id/edit' ,to: 'users#edit', as:'userEditp'
  patch "users/:id" => "users#update", as: "user_update"

  resources :votes

  resources :participants

  resources :notifications

  Rails.application.routes.draw do
    resources :users, controller: 'users', only: Clearance.configuration.user_actions
  end

  get 'whatis/index'

  resources :notes

  resources :boards

  resources :dynamics
  get '/dynamics/:id/info', to: 'dynamics#info', as: 'info'
  get '/dynamics/:id/addParticipant', to: 'dynamics#addParticipant', as: 'addParticipant'
  get '/dynamics/:id/addBoard', to: 'dynamics#addBoard', as: 'addBoard'
  get '/dynamics/:id/statistics', to: 'dynamics#statistics', as: 'statistics'
  get '/dynamics/:id/votingResults', to: 'dynamics#votingResults', as: 'votingResults'
  get '/boards/:id/addNote', to: 'boards#addNote', as: 'addNote'

  get '/boards/:id/moveNotes', to: 'boards#moveNotes', as: 'moveNotes'
  get '/boards/:id/votation', to: 'boards#votation', as: 'votation'

  get '/dynamics/:id/leave', to: 'dynamics#leave', as: 'leave'
  get '/dynamics/:id/activateVotation', to: 'dynamics#activateVotation', as: 'activateVotation'

  get 'box' => 'welcome#box'
  get 'design' => 'welcome#index'

  root 'dynamics#index'

end

app/models/dynamic.rb
class Dynamic < ActiveRecord::Base
  belongs_to :user
  has_many :boards
  accepts_nested_attributes_for :boards
  has_many :participants
  has_many :notes
  has_many :votes
end

app/controllers/dynamics_controller.rb
class DynamicsController < ApplicationController
  before_action :set_dynamic, only: [:show, :edit, :update, :destroy, :addBoard, :addParticipant, :info, :leave, :activateVotation, :statistics, :votingResults]
  before_action :require_login

  include DynamicsHelper

  # GET /dynamics
  # GET /dynamics.json
  def index
    @dynamics = Dynamic.all
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def info 
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end 

  def edit
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participant = Participant.new
    @participants = Participant.all
  end

  def leave
    Participant.where(email: current_user.email,dynamic_id:@dynamic.id).destroy_all
    Notification.create :user_id => current_user.id , :text => "You left dynamic #{@dynamic.name}", :estado => false
    redirect_to "/dynamics/"
  end

  def statistics
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
    @total_notes = Note.where(dynamic_id:@dynamic.id).size
    @total_boards = Board.where(dynamic_id:@dynamic.id).size - 2
    @total_participants= (Participant.where(dynamic_id:@dynamic.id) & Participant.where.not(avatar_file_name: nil) & Participant.where.not(name: nil)).size
    note_aux
    @char_note = notes
  end

  def votingResults
    @total_participants= (Participant.where(dynamic_id:@dynamic.id) & Participant.where.not(avatar_file_name: nil) & Participant.where.not(name: nil)).size
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
    @partVoted = Vote.where(dynamic_id:@dynamic.id).pluck('Distinct participant_id').size
    
    votes_aux
    @char_vote = votes
  end

  def votes_aux
    @typ =  Note.where(id:Vote.where(dynamic_id:@dynamic.id).map(&:note_id)).map(&:numerodanota)
    @typ_ids = Vote.where(dynamic_id:@dynamic.id).map(&:note_id)
    @number = []
    @typ_ids.each do |t|
      @number << Vote.pluck(:note_id).select { |a| a == t }.size
    end
  end

  def note_aux
    @typ =  (Board.where.not(name: "all notes") & Board.where.not(name:"without board") &  Board.where(dynamic_id:@dynamic.id)).map(&:name)
    @typ_ids = (Board.where.not(name: "all notes") & Board.where.not(name:"without board") &  Board.where(dynamic_id:@dynamic.id)).map(&:id)
    @number = []
    @typ_ids.each do |t|
      @number << Note.pluck(:board_id).select { |a| a == t }.size
    end
  end

  def activateVotation
    d=Dynamic.where(id:@dynamic.id).last
    d.votation=true
    d.save
    Notification.create :user_id => current_user.id , :text => "You activated the votation in dynamic #{@dynamic.name}", :estado => false
    redirect_to "/dynamics/#{@dynamic.id}"
  end 

  # GET /dynamics/1
  # GET /dynamics/1.json
  def show
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def addBoard
    @board= Board.new
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participants = Participant.all
  end

  def addParticipant
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @participant = Participant.new
    @participants = Participant.all
  end

  # GET /dynamics/new
  def new
    @notificationss =  Notification.where(user_id:current_user.id,estado:false).size
    @dynamic = Dynamic.new    
  end

  # GET /dynamics/1/edit

  # POST /dynamics
  # POST /dynamics.json
  def create
    @dynamic = Dynamic.new(dynamic_params)
    respond_to do |format|
      if @dynamic.save
        format.html { redirect_to @dynamic}
        format.json { render :show, status: :created, location: @dynamic }
      else
        format.html { render :new }
        format.json { render json: @dynamic.errors, status: :unprocessable_entity }
      end
    end
      if @dynamic.name==""
        @dynamic.name="undefined"
        @dynamic.save
      end
      if @dynamic.descricao==""
        @dynamic.descricao="undefined"
        @dynamic.save
      end
      if @dynamic.final==nil
        @dynamic.final = DateTime.now + 2.hour
        @dynamic.save
      end
      if @dynamic.votationnumber==nil
        @dynamic.votationnumber = 3
        @dynamic.save
      end
    Board.create :dynamic_id => @dynamic.id , :color=>"boardCinza", :name=> "all notes"
    Board.create :dynamic_id => @dynamic.id , :color=>"boardCinza", :name=> "without board"
    Participant.create :dynamic_id => @dynamic.id , :email=>current_user.email, :vote => false
    Notification.create :user_id => current_user.id , :text => "You created dynamic #{@dynamic.name}", :estado => false
  end

  # PATCH/PUT /dynamics/1
  # PATCH/PUT /dynamics/1.json
  def update
    respond_to do |format|
      if @dynamic.update(dynamic_params)
        format.html { redirect_to @dynamic}
        format.json { render :show, status: :ok, location: @dynamic }
      else
        format.html { render :edit }
        format.json { render json: @dynamic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamics/1
  # DELETE /dynamics/1.json
  def destroy
    @dynamic.destroy
    respond_to do |format|
      format.html { redirect_to dynamics_url }
      format.json { head :no_content }
    end
    Notification.create :user_id => current_user.id , :text => "You destroyed dynamic #{@dynamic.name}" , :estado => false
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_dynamic
      @dynamic = Dynamic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dynamic_params
      #params.require(:dynamic).permit(:name, :descricao)
       params.require(:dynamic).permit(:name, :descricao, :user_id,:color,:final,:numerodenotas,:votation,:votationnumber, boards_attributes: [ :name, :descricao ],participants_attributes: [ :email ], notes_attributes: [ :text ])
    end

    def notes
      LazyHighCharts::HighChart.new('graph') do |f|
        f.title(text: 'Number of notes per board')
        f.xAxis(categories:(Board.where.not(name: "all notes") & Board.where.not(name:"without board") &  Board.where(dynamic_id:@dynamic.id)).map(&:name))
        f.series(name: 'Boards', yAxis: 0, data: @number)
        f.yAxis [{ allowDecimals: false, title: { text: 'Number of notes', margin: 70 } }]
        f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
        f.chart(defaultSeriesType: 'column')
      end
    end

    def votes
      LazyHighCharts::HighChart.new('graph') do |f|
        f.title(text: 'Number of votes per note')
        f.xAxis(categories: (Note.where(id:Vote.where(dynamic_id:199).map(&:note_id)).map(&:numerodanota)))
        f.series(name: 'Notes', yAxis: 0, data: @number)
        f.yAxis [{ allowDecimals: false, title: { text: 'Number of votes', margin: 70 } }]
        f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
        f.chart(defaultSeriesType: 'column')
      end
    end
end

app/helpers/dynamics_helper.rb
module DynamicsHelper
end

app/views/dynamics/_formBoard.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br><br>
    <div class="input-letter"><%= f.text_field :name ,:placeholder=>"Name",:style => 'text-align:center;background-image: url("");',:class=>'form-control'  %></div>
  </div>
  <br>
  <div class="letrasInfo2">color: </div>
  <div class="field">
    <%= select(:board,:color, [
      ['Red', "boardRed"],
      ['Turquoise', "boardAzul"],
      ['Orange', "boardLaranja"],
      ['Yellow', "boardAmarelo"],
      ['Blue', "boardAzulClaro"],
      ['Purple', "boardRoxo"],
      ['Brown', "boardCastanho"],
      ['Green', "boardVerde"],
    ])%>
  </div>
  <%= f.hidden_field :dynamic_id, value: @dynamic.id %>
  <br>
  <div class="actions">
    <%= button_to "Submit", dynamics_path, method: :submit,:type =>type="button",:class=>'btn btn-success' %> 
  </div>
  <br><br>
  <div class= "hh3">
    <%= link_to "/dynamics/#{@dynamic.id}" , method: :get , :class => "hvr-icon-back" do %> 
      Back to Dynamic
    <% end %>
  </div>
  <br><br>
<% end %>

app/views/dynamics/_formTopBarB.html.erb
<div id="topo">
  <%= link_to dynamics_path , method: :get  do %>
    <div class="topo-Logo wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
      IDeaTouch
    </div>
  <% end %>   
  <%= link_to sign_out_path, method: :delete  do %>
    <div class="topo-perfil wow fadeInRight" data-wow-duration="0.6s" data-wow-delay="0.6s">
      <i class="fa fa-power-off"></i>
    </div>
  <% end %>

  <!-- sino notificaçoes -->
  <% if @notificationss!=0 %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="hvr-buzz-out">
        <div class="topo-perfil2 wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
          <i class="fa fa-bell"></i>
        </div>  
      </div>
    <% end %>
  <% else %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="topo-perfil wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
         <i class="fa fa-bell-o"></i>
      </div>
    <% end %>
    <!-- -->
  <% end %>
  <%= link_to "/users/#{current_user.id}/edit", method: :get  do %>
    <div class="topo-perfil wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.8s">
      <i class="fa fa-user"></i>
    </div>
  <% end %>
  <div class="topo-perfilF wow fadeInUp" data-wow-duration="1.0s" data-wow-delay="1.0s">
    <% if @participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.avatar_file_name!= nil %>
      <%= link_to  edit_participant_path(@participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.id) , method: :get  do %>
          <%= image_tag @participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.avatar.url(:medium) , size: "60x70" %>
      <% end %>
    <% else %>
      <%= link_to  edit_participant_path(@participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.id) , method: :get  do %>
        <div class= "avatar">
          <h2><i class="fa fa-user-secret"></i></h2>
        </div>
      <% end %> 
    <% end %>
  </div>
  <div class="topo-nome wow fadeInRight" data-wow-duration="1.5s" data-wow-delay="1.5s">
    <%if @participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.name != nil %>
      <div class="serif"><%=@participants.where(email:current_user.email, dynamic_id:@board.dynamic.id).last.name%></div>
    <% else %>
      <div class="serif">edit your name</div>
    <% end %>   
  </div>
</div>

app/views/dynamics/_formTopBarN.html.erb
<div id="topo">
  <%= link_to dynamics_path , method: :get  do %>
    <div class="topo-Logo wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
      IDeaTouch
    </div>
  <% end %>
  <%= link_to sign_out_path, method: :delete  do %>
    <div class="topo-perfil wow fadeInRight" data-wow-duration="0.6s" data-wow-delay="0.6s">
      <i class="fa fa-power-off"></i>
    </div>
  <% end %>

  <!-- sino notificaçoes -->
  <% if @notificationss!=0 %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="hvr-buzz-out">
        <div class="topo-perfil2 wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
          <i class="fa fa-bell"></i>
        </div>  
      </div>
    <% end %>
  <% else %>
    <%= link_to notifications_path , method: :get  do %>
      <div class="topo-perfil wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
         <i class="fa fa-bell-o"></i>
      </div>
    <% end %>
    <!-- -->
  <% end %>
  <%= link_to "/users/#{current_user.id}/edit", method: :get  do %>
    <div class="topo-perfil wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.8s">
      <i class="fa fa-user"></i>
    </div>
  <% end %>
  <div class="topo-perfilF wow fadeInUp" data-wow-duration="1.0s" data-wow-delay="1.0s">
    <% if @participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.avatar_file_name!= nil %>
      <%= link_to  edit_participant_path(@participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.id) , method: :get  do %>
        <%= image_tag @participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.avatar.url(:medium) , size: "60x70" %>
      <% end %>
    <% else %>
      <%= link_to  edit_participant_path(@participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.id) , method: :get  do %>
        <div class= "avatar">
          <h2><i class="fa fa-user-secret"></i></h2>
        </div>
      <% end %> 
    <% end %>
  </div>
  <div class="topo-nome wow fadeInRight" data-wow-duration="1.5s" data-wow-delay="1.5s">
    <%if @participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.name != nil %>
      <div class="serif"><%=@participants.where(email:current_user.email, dynamic_id:@note.dynamic_id).last.name%></div>
    <% else %>
      <div class="serif">edit your name</div>
    <% end %>   
  </div>
</div>

app/views/dynamics/show.html.erb
<html>
  <head>
    <link rel="stylesheet" href="css/animate.css">
    <style>.wow:first-child {visibility: hidden;}</style>
    <title>IdeaTouch</title>
  </head>

  <body>
    <div class="preload"></div>
    <div class="content">
      <%= render 'formTopBarD' %>
      <div id = "topo2">
        <div class="caixa-icon wow fadeInLeft" data-wow-duration="0.4s" data-wow-delay="0.4s">
          <span class="glyphicon glyphicon-menu-right" aria-hidden="true" ></span>
        </div>
        <%= link_to "/dynamics" , method: :get  do %>
        <div class="wow fadeInLeft" data-wow-duration="0.5s" data-wow-delay="0.5s">
          <div class="hvr-float">
            <% if @dynamic.color=="dynamicCinza" %>
              <div class="caixa-menu cinza lifted">
            <% end %>
            <% if @dynamic.color=="dynamicAzul" %>
              <div class="caixa-menu azul lifted">
            <% end %>
            <% if @dynamic.color=="dynamicLaranja" %>
              <div class="caixa-menu laranja lifted">
            <% end %>
            <% if @dynamic.color=="dynamicAmarelo" %>
              <div class="caixa-menu amarelo lifted">
            <% end %>
            <% if @dynamic.color=="dynamicRed" %>
              <div class="caixa-menu red lifted">
            <% end %>
            <% if @dynamic.color=="dynamicAzulClaro" %>
              <div class="caixa-menu azulClaro lifted">
            <% end %>
            <% if @dynamic.color=="dynamicRoxo" %>
              <div class="caixa-menu roxo lifted">
            <% end %>
            <% if @dynamic.color=="dynamicCastanho" %>
              <div class="caixa-menu castanho lifted">
            <% end %>
            <% if @dynamic.color=="dynamicVerde" %>
              <div class="caixa-menu verde lifted">
            <% end %>
            <div class="letraTitulo"> 
              Dynamic 
            </div>
            <div class="letraSimbolo"> 
              <% if current_user.id == @dynamic.user_id %>
                <span class="glyphicon glyphicon-king" aria-hidden="true" ></span>
              <% end %>
            </div>
            <div class="letraNome"> 
              <%= link_to "/dynamics" , method: :get , :class => "hvr-icon-back" do %> 
                <div class="serif"><%= @dynamic.name %></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="wow fadeInRight" data-wow-duration="0.7s" data-wow-delay="0.7s">
      <div class="caixa-relogio lifted" >
        <div class="letraRelogio ">
          <% if  (@dynamic.final.to_time - 1.hours) > Time.now %>
            <div class="serif"><%= distance_of_time_in_words(Time.now, (@dynamic.final.to_time - 1.hours) , include_seconds: true) %> to the end</div>
            <span class="glyphicon glyphicon-time" aria-hidden="true"></spam>
          <% else %> 
          <div class="serif">finished</div>
          <span class="glyphicon glyphicon-record" aria-hidden="true"></spam>
        <% end %>
        </div>
        </div>
      </div>
    </div>
    <br><br><br>
    <div id="box-2">
      <br><br>
      <%= link_to info_path , method: :get  do %>
        <div class="fora">
          <div class="hvr-bob">
            <div class="lateral-perfil wow fadeInUp" data-wow-duration="0.3s" data-wow-delay="0.3s">
              <i class="fa fa-info"></i>
            </div>
          </div>
          <div id="hover-content">
            <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
              <div class="lateral2-perfil lifted">Dynamic Info</div></div>
          </div>
        </div>
      <%end %>
      <br><br><br>
      <% if current_user.id != @dynamic.user_id %>
        <%= link_to leave_path , method: :get  do %>
          <br><br><br>
          <div class="fora">
            <div class="hvr-bob">
              <div class="lateral-perfil3 wow fadeInUp" data-wow-duration="0.3s" data-wow-delay="0.3s">
                <i class="fa fa-reply"></i>
              </div>
            </div>
            <div id="hover-content">
              <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
              <div class="lateral3-perfil lifted">Leave Dynamic</div></div>
            </div>
          </div>
        <%end %>
        <br><br><br>
      <% end %>

      <!--- Restriçoes de funcionalidades -->
      <% if current_user.id == @dynamic.user_id %>
        <%= link_to statistics_path(@dynamic.id) , method: :get  do %>
        <div class="fora">
          <div class="hvr-bob">
            <div class="lateral-perfil wow fadeInUp" data-wow-duration="0.4s" data-wow-delay="0.4s">
              <i class="fa fa-pie-chart"></i>
            </div>
          </div>
          <div id="hover-content">
            <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
               <div class="lateral2-perfil lifted">Statistics</div></div>
          </div>
        </div>
      <%end%>
      <br><br><br>
      <% if  (@dynamic.final.to_time - 1.hours) < Time.now and @dynamic.votation==false %>
        <%= link_to activateVotation_path , method: :get  do %>
        <div class="fora">
          <div class="hvr-bob">
            <div class="lateral-perfil2 wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.5s">
              <i class="fa fa-archive"></i>
            </div>
          </div>
          <div id="hover-content">
            <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
               <div class="lateral2-perfil lifted">Activate voting</div></div>
          </div>
        </div>
        <br><br><br>
      <% end %>
    <% end%>
    <% if  (@dynamic.final.to_time - 1.hours) < Time.now and @dynamic.votation==true %>
      <%= link_to votingResults_path(@dynamic.id) , method: :get  do %>
        <div class="fora">
          <div class="hvr-bob">
            <div class="lateral-perfil wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.5s">
              <i class="fa fa-archive"></i>
            </div>
          </div>
          <div id="hover-content">
            <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
              <div class="lateral2-perfil lifted">Voting Results</div></div>
          </div>
        </div>
        <br><br><br>
      <% end %>
    <% end %>
    <% if (@dynamic.final.to_time - 1.hours) > Time.now %> 
      <%= link_to addParticipant_path , method: :get  do %>
        <div class="fora">
          <div class="hvr-bob">
            <div class="lateral-perfil wow fadeInUp" data-wow-duration="0.6s" data-wow-delay="0.6s">
              <i class="fa fa-user-plus"></i>
            </div>
          </div>
          <div id="hover-content">
            <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
               <div class="lateral2-perfil lifted">Invite people</div></div>
          </div>
        </div>
      <% end %>
      <br><br><br>
    <% end %>
    <%= link_to edit_dynamic_path , method: :get  do %>
      <div class="fora">
        <div class="hvr-bob">
          <div class="lateral-perfil wow fadeInUp" data-wow-duration="0.7s" data-wow-delay="0.7s">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></spam>
          </div>
        </div>
        <div id="hover-content">
          <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
            <div class="lateral2-perfil lifted">Edit Dynamic</div></div>
        </div>
      </div>
      <br><br><br>
    <% end %>        
    <%= link_to @dynamic, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <br><br><br>
      <div class="fora">
        <div class="hvr-bob">
          <div class="lateral-perfil3 wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.8s">
            <i class="fa fa-trash-o"></i>
          </div>
        </div>
        <div id="hover-content">
          <div class="wow fadeInLeft" data-wow-duration="0.2s" data-wow-delay="0.2s">
            <div class="lateral3-perfil lifted">Delete Dynamic</div>
          </div>
        </div>
      </div>
    <% end %><% end %>
    </div>
    <div id="box-3" class="box">
      <% for board in @dynamic.boards %>
        <% if board.name=="without board" and current_user.id == @dynamic.user_id %>
          <div class="hvr-float">
            <div class = "hvr-curl-top-left2 wow fadeInRight" data-wow-duration="0.5s" data-wow-delay="0.5s" >
            	<%= link_to board , method: :get  do %>
             	  <div class=<%= board.color%>> 
                  <h2>Board</h2> 
                  <div class="serif"><%= board.name %></div>
              	</div>
              <% end %>
            </div>
          </div>
          <% elsif board.name!="without board"%>
            <div class="hvr-float">
              <div class = "hvr-curl-top-left2 wow fadeInRight" data-wow-duration="0.5s" data-wow-delay="0.5s" >
                <%= link_to board , method: :get  do %>
                  <div class=<%= board.color%>> 
                    <h2>Board</h2> 
                    <div class="serif"><%= board.name %></div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <% if current_user.id == @dynamic.user_id %>
          <%= link_to "/dynamics/#{@dynamic.id}/addBoard" , method: :get  do %>
            <div class="hvr-float">
              <div class="boardMenu wow fadeInUp" data-wow-duration="0.4s" data-wow-delay="0.4s"> 
                <div class="hh1">
                  <i class="fa fa-plus-square-o"></i>
                </div>
                <div class="hh2"> New Board</div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <script src="js/wow.js"></script>
      <script>wow = new WOW({animateClass:'animated',offset:100,
        callback:function(box){console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")}});
        wow.init();
        document.getElementById('moar').onclick = function() {
          var section = document.createElement('section');
          section.className = 'section--purple wow fadeInDown';
          this.parentNode.insertBefore(section, this);};
      </script>
      <script>
        $(function() {
          $(".preload").fadeOut(10, function() {
            $(".content").fadeIn(10);        
          });
        });
      </script>
      <script>
        $(window).resize(setDivVisibility);
        function setDivVisibility(){
          if (($(window).width()) < '520'){  
            $('#topo2').css('height','100px');  
          } else {  
            $('#topo2').css('height','50px');  
          } 
        }
      </script>
      <script>
        $(window).load(setDivVisibility);
        function setDivVisibility(){
          if (($(window).width()) < '520'){  
            $('#topo2').css('height','100px');  
          } else {  
            $('#topo2').css('height','50px');  
          } 
        }
      </script>
      <script>
        $(".lateral-perfil").mouseover(function() {
          $('#box-2').css('width','185px');  
        }).mouseout(function() {
          $('#box-2').css('width','62px');  
        });
    </script>
  </body>
</html>